### ISSUE TITLE
请问效果图是web的还是mobile的 还是其他什么分支的？

### ISSUE THREAD

**Issue by jinjin123** [duqian42707/spring-boot-angular#1]
我部署之后web展现的效果少了很多东西 跟你的效果图不一致，有时间的话 请说明一下 谢谢

**Comment by duqian42707** [comment]
效果图是web的，mobile的没时间写了。东西少，应该是没有初始数据的原因。我重新导了一份sql，包含了系统运行必要的初始数据。重新执行一下sql就好。

**Comment by jinjin123** [comment]
@duqian42707  感谢百忙之中回复，已经可以了 谢谢
